---

baseURL: 'https://securitytxt.cz'
languageCode: 'cs-cz'
theme: "hugo-coder"
title: "security.txt"


markup:
  markup.highlight:
    style: "onesenterprise"


menu:
  main:
  - name: "Kdo používá"
    weight: 10
    url: "kdo-pouziva-security-txt"
  - name: O security.txt
    url: "/"
    weight: 1
  - name: RFC9116
    weight: 100
    url: "https://www.rfc-editor.org/rfc/rfc9116"